name: AdvancementsBingo
author: Natsuko
version: 0.1
main: com.natsuko.advancementsbingo.Plugin
api-version: 1.19

commands:
  ab:
    description: Your description
    usage: /ab <add/remove/teams/pick/list/start>
